version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.0

    steps:
      - checkout
      
      - run:
          name: install spectacles
          command: |
            python3 -m venv venv
            . venv/bin/activate
            git clone git@github.com:spectacles-ci/spectacles.git
            cd spectacles
            pip3 install . --user

      - run:
          name: spectacles connect
          command: |
            . venv/bin/activate
            spectacles connect -v

      - run:
          name: spectacles sql
          command: |
            . venv/bin/activate 
            spectacles sql --project welcome_to_looker --branch $CIRCLE_BRANCH --batch -v

workflows:
  version: 2
  test:
    jobs:
      - test

